// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package learn.grpc.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learn.grpc.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .learn.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<learn.grpc.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .learn.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  learn.grpc.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .learn.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .learn.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends learn.grpc.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .learn.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  learn.grpc.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
