// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package learn.grpc.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_grpc_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_grpc_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_grpc_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_grpc_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_grpc_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_grpc_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_grpc_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_grpc_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_grpc_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_grpc_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_grpc_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_grpc_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_grpc_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_grpc_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\020learn.grpc.proto\"\035\n\tMyR" +
      "equest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020" +
      "\n\010realName\030\002 \001(\t\"\035\n\016StudentRequest\022\013\n\003ag" +
      "e\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t" +
      "\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"Q\n\023StudentRe" +
      "sponseList\022:\n\017studentResponse\030\001 \003(\0132!.le" +
      "arn.grpc.proto.StudentResponse\"%\n\rStream" +
      "Request\022\024\n\014request_info\030\001 \001(\t\"\'\n\016StreamR" +
      "esponse\022\025\n\rresponse_info\030\001 \001(\t2\377\002\n\016Stude" +
      "ntService\022T\n\025GetRealNameByUsername\022\033.lea" +
      "rn.grpc.proto.MyRequest\032\034.learn.grpc.pro" +
      "to.MyResponse\"\000\022[\n\020GetStudentsByAge\022 .le" +
      "arn.grpc.proto.StudentRequest\032!.learn.gr" +
      "pc.proto.StudentResponse\"\0000\001\022g\n\030GetStude" +
      "ntsWrapperByAges\022 .learn.grpc.proto.Stud" +
      "entRequest\032%.learn.grpc.proto.StudentRes" +
      "ponseList\"\000(\001\022Q\n\006BiTalk\022\037.learn.grpc.pro" +
      "to.StreamRequest\032 .learn.grpc.proto.Stre" +
      "amResponse\"\000(\0010\001B\"\n\020learn.grpc.protoB\014St" +
      "udentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_learn_grpc_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_learn_grpc_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_grpc_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_learn_grpc_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_learn_grpc_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_grpc_proto_MyResponse_descriptor,
        new java.lang.String[] { "RealName", });
    internal_static_learn_grpc_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_learn_grpc_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_grpc_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_learn_grpc_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_learn_grpc_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_grpc_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_learn_grpc_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_learn_grpc_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_grpc_proto_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_learn_grpc_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_learn_grpc_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_grpc_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_learn_grpc_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_learn_grpc_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_grpc_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
